version: "3"

services:

  runtime-setup:
    image: vscode-swift:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-jammy"

  test:
    image: vscode-swift:22.04-main

  shell:
    image: vscode-swift:22.04-main
