services:

  runtime-setup:
    image: vscode-swift:20.04-5.8
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.8"

  test:
    image: vscode-swift:20.04-5.8

  shell:
    image: vscode-swift:20.04-5.8
